//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLookup
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catagory
    {
        public Catagory()
        {
            this.PIDevice = new HashSet<PIDevice>();
            this.PIPlayQueue = new HashSet<PIPlayQueue>();
        }
    
        public int idCatagory { get; set; }
    
        public virtual ICollection<PIDevice> PIDevice { get; set; }
        public virtual Musik Musik { get; set; }
        public virtual ICollection<PIPlayQueue> PIPlayQueue { get; set; }
    }
}
