//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLookup
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musik
    {
        public Musik()
        {
            this.PIAlbum = new HashSet<PIAlbum>();
            this.PIArtist = new HashSet<PIArtist>();
            this.PIGenre = new HashSet<PIGenre>();
        }
    
        public int Catagory_idCatagory { get; set; }
    
        public virtual Catagory Catagory { get; set; }
        public virtual ICollection<PIAlbum> PIAlbum { get; set; }
        public virtual ICollection<PIArtist> PIArtist { get; set; }
        public virtual ICollection<PIGenre> PIGenre { get; set; }
    }
}
