//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLookup
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIDevice
    {
        public PIDevice()
        {
            this.PIFilePath = new HashSet<PIFilePath>();
        }
    
        public string UUIDDevice { get; set; }
        public string IP { get; set; }
        public string PCOwner { get; set; }
        public string Protocol { get; set; }
        public int Catagory_idCatagory { get; set; }
        public Nullable<bool> Online { get; set; }
    
        public virtual Catagory Catagory { get; set; }
        public virtual ICollection<PIFilePath> PIFilePath { get; set; }
    }
}
