//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLookup
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PiindexEntities : DbContext
    {
        public PiindexEntities()
            : base("name=PiindexEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Catagory> Catagory { get; set; }
        public DbSet<Musik> Musik { get; set; }
        public DbSet<PIAlbum> PIAlbum { get; set; }
        public DbSet<PIArtist> PIArtist { get; set; }
        public DbSet<PIDevice> PIDevice { get; set; }
        public DbSet<PIFilePath> PIFilePath { get; set; }
        public DbSet<PIGenre> PIGenre { get; set; }
        public DbSet<PIMusikData> PIMusikData { get; set; }
        public DbSet<PIPlayQueue> PIPlayQueue { get; set; }
    }
}
